const themes = [
  {
    name: "Sleek",
    imgKey: 0,
    mainColor: "#212123",
    secondaryColor: "#585b60",
    textColor: "#eceff5",
    headerColor: "#212123",
    headerSecondary: "#585b60",
    headerText: "#eceff5",
    selector: "#585b60",
    contrastOne: "#d7d950",
    contrastTwo: "#68c2c8",
    blendMode: "normal",
  },
  {
    name: "Greyscale",
    imgKey: 1,
    mainColor: "#bebebe",
    secondaryColor: "#7b7b7b",
    textColor: "#6f6f6f",
    headerColor: "#262626",
    headerSecondary: "#ffffff",
    headerText: "#ffffff",
    selector: "#ffffff",
    contrastOne: "#e9e9e9",
    contrastTwo: "#646464",
    blendMode: "color-dodge",
  },
  {
    name: "Light",
    imgKey: 2,
    mainColor: "#ffffff",
    secondaryColor: "#ffffff",
    textColor: "#000000",
    headerColor: "#ffffff",
    headerSecondary: "#000000",
    headerText: "#000000",
    selector: "#ffffff",
    contrastOne: "#000000",
    contrastTwo: "#000000",
    blendMode: "normal",
  },
  {
    name: "Dark",
    imgKey: 3,
    mainColor: "#000000",
    secondaryColor: "#000000",
    textColor: "#ffffff",
    headerColor: "#000000",
    headerSecondary: "#ffffff",
    headerText: "#ffffff",
    selector: "#000000",
    contrastOne: "#ffffff",
    contrastTwo: "#ffffff",
    blendMode: "normal",
  },
  {
    name: "Beast_Mode",
    imgKey: 4,
    mainColor: "#f0f2f1",
    secondaryColor: "#ff4848",
    textColor: "#484040",
    headerColor: "#ff4848",
    headerSecondary: "#3f2c2c",
    headerText: "#ffffff",
    selector: "#ff8080",
    contrastOne: "#64565b",
    contrastTwo: "#64565b",
    blendMode: "multiply",
  },
  {
    name: "Boutique",
    imgKey: 5,
    mainColor: "#2f416c",
    secondaryColor: "#111b59",
    textColor: "#ffc2c2",
    headerColor: "#fffff6",
    headerSecondary: "#ffc2c2",
    headerText: "#ffc2c2",
    selector: "#fffff6",
    contrastOne: "#ffb220",
    contrastTwo: "#f4c2ff",
    blendMode: "screen",
  },
]

export default themes
